"""GitHub Comment Renderer.

Formats validated LLM output into GitHub Markdown.
Zero business logic - only formatting.
"""

from __future__ import annotations

from typing import Any

from presentation.llm.models import LLMContext
from presentation.llm.validator import ValidatedComment


class GitHubCommentRenderer:
    """
    Renders validated LLM comment into GitHub Markdown.
    
    Responsibilities:
    - GitHub-specific formatting
    - Collapsible sections
    - Tables
    - Icons
    - Spacing
    
    Zero business logic. Only formatting.
    """
    
    def render(self, validated_comment: ValidatedComment, context: LLMContext | None = None) -> str:
        """
        Render validated comment to GitHub Markdown.
        
        Args:
            validated_comment: The validated LLM-generated comment.
            context: Optional LLMContext for additional formatting hints.
            
        Returns:
            GitHub-formatted markdown string.
        """
        # The validated comment is already markdown, but we can enhance it
        markdown = validated_comment.markdown
        
        # Add metadata footer
        markdown = self._add_metadata_footer(markdown, validated_comment)
        
        return markdown
    
    def render_fallback(self, context: LLMContext) -> str:
        """
        Render a deterministic fallback comment when LLM generation fails.
        
        Args:
            context: The LLMContext with deterministic discoveries.
            
        Returns:
            GitHub-formatted fallback markdown.
        """
        summary = context.summary
        
        markdown = """## 🔍 Factor Analysis Complete

This PR has been analyzed by Factor's deterministic compiler. Below is a summary of the findings.

### 📊 Change Overview

| Metric | Value |
|--------|-------|
| Changed Files | {changed_files} |
| Changed Symbols | {changed_symbols} |
| Affected Behaviors | {affected_behaviors} |
| Execution Paths | {execution_paths} |
| Services Reached | {services_reached} |
| Validation Gaps | {validation_gaps} |

### 🎯 Key Findings

The compiler identified **{surprising_discoveries}** surprising discoveries in this change.

<details>
<summary>📋 View Detailed Findings</summary>

The full analysis results are available in the API response. Key areas reviewed:

- ✅ Execution impact and reachability
- ✅ Operational surface (API, data, dependencies)
- ✅ Validation coverage and gaps
- ✅ Behavioral changes and propagation

</details>

### 💡 Next Steps

1. Review the detailed findings in the analysis results
2. Pay special attention to validation gaps
3. Consider the execution reach of modified symbols

---

*Generated by Factor - Deterministic Static Analysis*
""".format(
            changed_files=summary.get('changed_files', 0),
            changed_symbols=summary.get('changed_symbols', 0),
            affected_behaviors=summary.get('affected_behaviors', 0),
            execution_paths=summary.get('execution_paths', 0),
            services_reached=summary.get('services_reached', 0),
            validation_gaps=summary.get('validation_gaps', 0),
            surprising_discoveries=summary.get('surprising_discoveries', 0),
        )
        
        return markdown
    
    def _add_metadata_footer(self, markdown: str, validated_comment: ValidatedComment) -> str:
        """Add metadata footer to the comment."""
        footer = "\n\n---\n"
        
        if validated_comment.model:
            footer += f"*Generated by Factor using {validated_comment.model}*\n"
        else:
            footer += "*Generated by Factor*\n"
        
        if validated_comment.truncated:
            footer += "*⚠️ Comment was truncated due to length*\n"
        
        if not validated_comment.is_valid:
            footer += "*⚠️ Comment validation had warnings*\n"
        
        footer += "*All findings are grounded in deterministic compiler evidence*\n"
        
        return markdown + footer
    
    def render_discovery_table(self, discoveries: tuple[Any, ...], max_rows: int = 10) -> str:
        """
        Render discoveries as a GitHub Markdown table.
        
        Args:
            discoveries: Tuple of discovery objects (LLMDiscovery or similar).
            max_rows: Maximum number of rows to render.
            
        Returns:
            Markdown table string.
        """
        if not discoveries:
            return ""
        
        lines = []
        lines.append("| # | Discovery | Kind | Impact |")
        lines.append("|---|-----------|------|--------|")
        
        for i, discovery in enumerate(discoveries[:max_rows], 1):
            title = getattr(discovery, 'title', str(discovery))
            kind = getattr(discovery, 'kind', 'unknown')
            
            # Get impact metric
            impact = "N/A"
            if hasattr(discovery, 'metrics') and discovery.metrics:
                metrics = discovery.metrics
                # Use execution_reach as primary impact metric
                impact = str(metrics.get('execution_reach', 'N/A'))
            elif hasattr(discovery, 'surprise') and discovery.surprise:
                surprise = discovery.surprise
                if isinstance(surprise, dict):
                    impact = f"surprise: {surprise.get('max_ratio', 0):.2f}"
            
            # Truncate long titles
            if len(title) > 40:
                title = title[:37] + "..."
            
            lines.append(f"| {i} | {title} | {kind} | {impact} |")
        
        return "\n".join(lines)
    
    def render_metrics_table(self, metrics: dict[str, Any]) -> str:
        """
        Render metrics as a GitHub Markdown table.
        
        Args:
            metrics: Dictionary of metric names to values.
            
        Returns:
            Markdown table string.
        """
        if not metrics:
            return ""
        
        lines = []
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        
        for key, value in metrics.items():
            lines.append(f"| {key} | {value} |")
        
        return "\n".join(lines)