"""Intermediate representation for language-agnostic semantic graphs."""

from language_adapters.ir.nodes import (
    NodeType,
    BaseNode,
    FunctionNode,
    MethodNode,
    ClassNode,
    ModuleNode,
    DecoratorNode,
    EndpointNode,
    ModelNode,
    FieldNode,
    TableNode,
    ColumnNode,
    QueryNode,
    TransactionNode,
    MigrationNode,
    TestNode,
    EventNode,
    ExternalServiceNode,
    CacheNode,
    QueueNode,
)
from language_adapters.ir.edges import (
    EdgeType,
    BaseEdge,
    CallsEdge,
    CalledByEdge,
    ReadsEdge,
    WritesEdge,
    CreatesEdge,
    UpdatesEdge,
    DeletesEdge,
    UsesEdge,
    ValidatesEdge,
    NormalizesEdge,
    TestsEdge,
    MigratesEdge,
    ExposesEdge,
    PublishesEdge,
    SubscribesEdge,
    SendsHttpEdge,
    EmitsEventEdge,
    HasFieldEdge,
    HasParameterEdge,
    ReturnsEdge,
    RaisesEdge,
    InheritsEdge,
    DecoratedByEdge,
)
from language_adapters.ir.semantic_graph import SemanticGraph

__all__ = [
    # Nodes
    "NodeType",
    "BaseNode",
    "FunctionNode",
    "MethodNode",
    "ClassNode",
    "ModuleNode",
    "DecoratorNode",
    "EndpointNode",
    "ModelNode",
    "FieldNode",
    "TableNode",
    "ColumnNode",
    "QueryNode",
    "TransactionNode",
    "MigrationNode",
    "TestNode",
    "EventNode",
    "ExternalServiceNode",
    "CacheNode",
    "QueueNode",
    # Edges
    "EdgeType",
    "BaseEdge",
    "CallsEdge",
    "CalledByEdge",
    "ReadsEdge",
    "WritesEdge",
    "CreatesEdge",
    "UpdatesEdge",
    "DeletesEdge",
    "UsesEdge",
    "ValidatesEdge",
    "NormalizesEdge",
    "TestsEdge",
    "MigratesEdge",
    "ExposesEdge",
    "PublishesEdge",
    "SubscribesEdge",
    "SendsHttpEdge",
    "EmitsEventEdge",
    "HasFieldEdge",
    "HasParameterEdge",
    "ReturnsEdge",
    "RaisesEdge",
    "InheritsEdge",
    "DecoratedByEdge",
    # Graph
    "SemanticGraph",
]