[project]
name = "cystatic-core"
version = "0.1.0"
description = "Core package for Cystatic"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Jishnu Samal" }
]
dependencies = [
    "fastapi[all]>=0.128.8",
    "gunicorn>=23.0.0",
    "pygithub>=2.9.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "ruff>=0.6.0",
    "mypy>=1.10.0"
]