[project]
name = "factor-api"
version = "0.1.0"
description = "Factor API"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Jishnu Samal" }
]

dependencies = [
    "fastapi[all]==0.135.2",
    "gunicorn==25.3.0",
    "uvicorn==0.42.0",
    "pygithub==2.9.0",
    "python-dotenv==1.2.2",
    "unidiff==0.7.5",
    "amplitude-analytics==1.2.3",
    "sentry-sdk==2.56.0",
    "jinja2==3.1.6",
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "anyio==4.13.0",
    "certifi==2026.2.25",
    "cffi==2.0.0 ; platform_python_implementation != 'PyPy'",
    "charset-normalizer==3.4.7",
    "click==8.3.1",
    "colorama==0.4.6 ; sys_platform == 'win32'",
    "cryptography==46.0.6",
    "dnspython==2.8.0",
    "email-validator==2.3.0",
    "fastapi-cli==0.0.24",
    "fastapi-cloud-cli==0.15.1",
    "fastar==0.9.0",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httptools==0.7.1",
    "httpx==0.28.1",
    "idna==3.11",
    "itsdangerous==2.2.0",
    "markdown-it-py==4.0.0",
    "markupsafe==3.0.3",
    "mdurl==0.1.2",
    "packaging==26.0",
    "pycparser==3.0 ; implementation_name != 'PyPy' and platform_python_implementation != 'PyPy'",
    "pydantic==2.12.5",
    "pydantic-core==2.41.5",
    "pydantic-extra-types==2.11.1",
    "pydantic-settings==2.13.1",
    "pygments==2.19.2",
    "pyjwt==2.12.1",
    "pynacl==1.6.2",
    "python-multipart==0.0.22",
    "pyyaml==6.0.3",
    "requests==2.33.1",
    "rich==14.3.3",
    "rich-toolkit==0.19.7",
    "rignore==0.7.6",
    "shellingham==1.5.4",
    "starlette==1.0.0",
    "typer==0.24.1",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "urllib3==2.6.3",
    "uvloop==0.22.1 ; platform_python_implementation != 'PyPy' and sys_platform != 'cygwin' and sys_platform != 'win32'",
    "watchfiles==1.1.1",
    "websockets==16.0",
    "tortoise-orm[cli]>=1.1.7",
    "asyncpg>=0.31.0",
    "openai>=2.32.0",
    "pytest-asyncio>=1.4.0",
    "dramatiq>=2.1.0",
    "redis>=7.4.0",
    "pytest-cov>=7.1.0",
    "tiktoken>=0.13.0",
    "llmlingua>=0.2.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "ruff>=0.6.0",
    "mypy>=1.10.0"
]
