from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


# ---------------------------------------------------------------------------
# Limits (immutable, request-scoped)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ResolutionBudget:
    """Immutable, request-scoped resource limits for lazy resolution.

    Defaults are operational values chosen for safety; they should be
    configurable at the analysis-request boundary.

    max_files
        Maximum number of repository files materialized through lazy
        resolution.

    max_bytes
        Maximum source/blob bytes materialized.

    max_remote_requests
        Maximum provider/network requests generated by resolution.
        A batched provider call counts as 1 request.

    max_depth
        Maximum resolver frontier depth (impact traversal depth, not
        Python recursion depth).

    max_unresolved_symbols
        Maximum unique unresolved symbol requirements allowed in the
        active resolution process.
    """

    max_files: int = 500
    max_bytes: int = 50 * 1024 * 1024  # 50 MB
    max_remote_requests: int = 100
    max_depth: int = 20
    max_unresolved_symbols: int = 1_000


# Backward-compatibility alias so existing call-sites that reference
# ``MaterializationBudget`` continue to work without modification.
MaterializationBudget = ResolutionBudget


# ---------------------------------------------------------------------------
# Running usage (mutable, one instance per request)
# ---------------------------------------------------------------------------


@dataclass
class ResolutionUsage:
    """Cumulative resource consumption for a single resolution operation.

    Two concurrent analysis requests must never share a ResolutionUsage
    instance — no mutable global state should hold these values.
    """

    files: int = 0
    """Unique repository paths successfully materialized."""

    bytes: int = 0
    """Source bytes fetched during this resolution."""

    remote_requests: int = 0
    """Provider network calls made (batched calls count as 1)."""

    depth: int = 0
    """Current frontier traversal depth (updated each round)."""

    unresolved_symbols: int = 0
    """Unique unresolved symbol identities seen across all frontier iterations."""

    # Internal sets for deduplication — not part of the public serialisation API.
    _materialized_paths: set[str] = field(default_factory=set, repr=False, compare=False)
    _seen_symbol_ids: set = field(default_factory=set, repr=False, compare=False)

    # ------------------------------------------------------------------
    # Mutation helpers
    # ------------------------------------------------------------------

    def record_paths(self, paths: list[str], bytes_per_path: dict[str, int]) -> None:
        """Record newly materialized paths, deduplicating automatically.

        Deduplication ensures that if the same path appears in multiple
        frontier iterations it is counted only once.
        """
        for p in paths:
            if p not in self._materialized_paths:
                self._materialized_paths.add(p)
                self.files += 1
                self.bytes += bytes_per_path.get(p, 0)

    def record_remote_request(self) -> None:
        """Increment the remote-request counter by one."""
        self.remote_requests += 1

    def record_symbols(self, symbol_ids) -> None:
        """Record unresolved symbol ids, deduplicating across iterations.

        Example:
            iteration 1: {Foo, Bar}
            iteration 2: {Foo, Baz}
            → unresolved_symbols = 3  (Foo, Bar, Baz)
        """
        self._seen_symbol_ids.update(symbol_ids)
        self.unresolved_symbols = len(self._seen_symbol_ids)

    def snapshot(self) -> dict:
        """Return a machine-readable snapshot suitable for metrics emission."""
        return {
            "files": self.files,
            "bytes": self.bytes,
            "remote_requests": self.remote_requests,
            "depth": self.depth,
            "unresolved_symbols": self.unresolved_symbols,
        }


# ---------------------------------------------------------------------------
# Budget decision
# ---------------------------------------------------------------------------


class BudgetExceededReason(str, Enum):
    """Identifies which limit caused a budget decision to be denied."""

    MAX_FILES = "max_files"
    MAX_BYTES = "max_bytes"
    MAX_REMOTE_REQUESTS = "max_remote_requests"
    MAX_DEPTH = "max_depth"
    MAX_UNRESOLVED_SYMBOLS = "max_unresolved_symbols"


@dataclass(frozen=True)
class BudgetDecision:
    """Structured result of a pre-materialization budget check.

    Example (allowed)::

        BudgetDecision(allowed=True, reason=None)

    Example (denied)::

        BudgetDecision(allowed=False, reason=BudgetExceededReason.MAX_FILES)
    """

    allowed: bool
    reason: BudgetExceededReason | None = None


# ---------------------------------------------------------------------------
# Legacy exception (kept for backward-compatibility during transition)
# ---------------------------------------------------------------------------


class MaterializationBudgetExceeded(Exception):
    """Raised by legacy code paths.

    Phase 11 replaces the raise-on-exceed pattern with ``BudgetDecision``.
    This class is retained so that any external code that catches it does
    not break during the transition period.
    """

    pass


# ---------------------------------------------------------------------------
# Phase 12 — Resolution configuration
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ResolutionConfig:
    """Top-level, per-request configuration for the repository resolution layer.

    Bundles the immutable :class:`ResolutionBudget` with the Phase 12
    ``enable_full_index_fallback`` flag so callers can toggle fallback
    behaviour without touching resolver internals.

    Example — disable fallback for a focused request::

        config = ResolutionConfig(
            budget=ResolutionBudget(max_files=200),
            enable_full_index_fallback=False,
        )

    The default is to **enable** fallback whenever a ``FullIndexFallback``
    instance is wired into ``RepositoryView``.
    """

    budget: ResolutionBudget = field(default_factory=ResolutionBudget)
    enable_full_index_fallback: bool = True
