"""Tests for language-agnostic file role classification."""

import dataclasses

import pytest

from engine.change.passes.file_classification import (
    AnalysisPolicy,
    FileClassification,
    FileClassifier,
    FileKind,
    detect_language,
    is_analyzable,
)


@pytest.fixture
def classifier() -> FileClassifier:
    return FileClassifier()


class TestClassificationMatrix:
    """Spec acceptance matrix for path-based classification."""

    @pytest.mark.parametrize(
        "path,expected_kind",
        [
            # Frontend signals
            ("src/components/Button.tsx", FileKind.FRONTEND),
            ("src/pages/index.tsx", FileKind.FRONTEND),
            ("frontend/api/client.ts", FileKind.FRONTEND),
            ("web/utils/format.ts", FileKind.FRONTEND),
            ("client/App.tsx", FileKind.FRONTEND),
            ("ui/Modal.tsx", FileKind.FRONTEND),
            ("src/views/Dashboard.ts", FileKind.FRONTEND),
            # Backend signals
            ("server/api.ts", FileKind.BACKEND),
            ("backend/db.ts", FileKind.BACKEND),
            ("api/routes.ts", FileKind.BACKEND),
            ("worker/queue.ts", FileKind.BACKEND),
            ("workers/process.ts", FileKind.BACKEND),
            ("services/user_service.ts", FileKind.BACKEND),
            # Shared signals
            ("shared/types.ts", FileKind.SHARED),
            ("common/utils.ts", FileKind.SHARED),
            ("libs/math.ts", FileKind.SHARED),
            ("packages/shared/types.ts", FileKind.SHARED),
            # Generated takes precedence over normal roles
            ("generated/schema.ts", FileKind.GENERATED),
            ("__generated__/Query.tsx", FileKind.GENERATED),
            ("src/proto/service_pb2.py", FileKind.GENERATED),
            # Test markers
            ("tests/test_api.py", FileKind.TEST),
            ("src/__tests__/api.test.ts", FileKind.TEST),
            ("frontend/__tests__/Button.test.tsx", FileKind.TEST),
            ("services/user.spec.ts", FileKind.TEST),
            # Unknown: .ts alone must NOT mean frontend
            ("foo.ts", FileKind.UNKNOWN),
            ("src/utils/http.ts", FileKind.UNKNOWN),
        ],
    )
    def test_path_classification(
        self, classifier: FileClassifier, path: str, expected_kind: FileKind
    ):
        result = classifier.classify(path)
        assert result.kind == expected_kind, result.reason

    def test_tsx_component_is_frontend(self, classifier):
        assert classifier.classify("components/Button.tsx").kind == FileKind.FRONTEND

    def test_tsx_page_is_frontend(self, classifier):
        assert classifier.classify("pages/Home.tsx").kind == FileKind.FRONTEND

    def test_generated_precedence_over_frontend(self, classifier):
        result = classifier.classify("frontend/generated/apollo-types.ts")
        assert result.kind == FileKind.GENERATED

    def test_test_precedence_over_frontend(self, classifier):
        result = classifier.classify("frontend/components/Button.test.tsx")
        assert result.kind == FileKind.TEST

    def test_generated_content_marker(self, classifier):
        content = "// @generated by protoc\n// DO NOT EDIT!\nexport const x = 1;"
        result = classifier.classify("src/models.ts", content=content)
        assert result.kind == FileKind.GENERATED


class TestLanguageAgnostic:
    """Classification must not assume a language implies a role."""

    def test_typescript_backend_not_frontend(self, classifier):
        assert classifier.classify("server/handler.ts").kind == FileKind.BACKEND

    def test_typescript_shared_not_frontend(self, classifier):
        assert classifier.classify("shared/index.ts").kind == FileKind.SHARED

    def test_python_file_classified_by_role_not_language(self, classifier):
        assert classifier.classify("services/billing.py").kind == FileKind.BACKEND

    def test_java_file_unknown_without_signals(self, classifier):
        assert classifier.classify("Service.java").kind == FileKind.UNKNOWN

    def test_no_language_plugin_dependencies(self):
        import inspect

        from engine.change.passes import file_classification as fc

        source = inspect.getsource(fc)
        assert "engine.language" not in source
        assert "tree_sitter" not in source


class TestDeterminismAndImmutability:
    """Classification is immutable and deterministic."""

    def test_classification_is_frozen(self):
        c = FileClassification(kind=FileKind.UNKNOWN, confidence=0.0, reason="r")
        with pytest.raises(dataclasses.FrozenInstanceError):
            c.kind = FileKind.FRONTEND  # type: ignore[misc]

    def test_deterministic_for_same_input(self, classifier):
        for path in (
            "src/components/Button.tsx",
            "server/api.ts",
            "foo.ts",
            "generated/x.ts",
        ):
            assert classifier.classify(path) == classifier.classify(path)

    def test_confidence_bounds(self, classifier):
        for path in (
            "a.ts",
            "src/components/A.tsx",
            "server/a.ts",
            "shared/a.ts",
            "generated/a.ts",
            "config.json",
        ):
            result = classifier.classify(path)
            assert 0.0 <= result.confidence <= 1.0

    def test_kind_enum_values(self):
        assert FileKind("frontend") == FileKind.FRONTEND
        assert {k.value for k in FileKind} == {
            "frontend",
            "backend",
            "shared",
            "generated",
            "config",
            "test",
            "migration",
            "docs",
            "infrastructure",
            "unknown",
        }


class TestAnalysisEligibility:
    """is_analyzable / AnalysisPolicy acceptance criteria."""

    def test_frontend_tsx_included(self):
        c = FileClassification(FileKind.FRONTEND, 0.85, "")
        assert is_analyzable(c, "typescript")

    def test_frontend_js_included(self):
        c = FileClassification(FileKind.FRONTEND, 0.85, "")
        assert is_analyzable(c, "javascript")

    def test_frontend_python_still_eligible(self):
        c = FileClassification(FileKind.FRONTEND, 0.85, "")
        assert is_analyzable(c, "python")

    def test_backend_ts_eligible(self):
        c = FileClassification(FileKind.BACKEND, 0.8, "")
        assert is_analyzable(c, "typescript")

    def test_shared_ts_eligible(self):
        c = FileClassification(FileKind.SHARED, 0.75, "")
        assert is_analyzable(c, "typescript")

    def test_generated_always_excluded(self):
        for language in ("typescript", "python", "java", ""):
            c = FileClassification(FileKind.GENERATED, 0.95, "")
            assert not is_analyzable(c, language)

    def test_unknown_ts_eligible(self):
        c = FileClassification(FileKind.UNKNOWN, 0.0, "")
        assert is_analyzable(c, "typescript")

    def test_policy_should_materialize_matches_analysis(self):
        policy = AnalysisPolicy()
        frontend = FileClassification(FileKind.FRONTEND, 0.85, "")
        backend = FileClassification(FileKind.BACKEND, 0.8, "")
        generated = FileClassification(FileKind.GENERATED, 0.95, "")

        assert policy.should_materialize(frontend, "typescript")
        assert not policy.should_materialize(generated, "python")
        assert policy.should_materialize(backend, "typescript")


class TestDetectLanguage:
    def test_extensions(self):
        assert detect_language("a.ts") == "typescript"
        assert detect_language("a.tsx") == "typescript"
        assert detect_language("a.js") == "javascript"
        assert detect_language("a.jsx") == "javascript"
        assert detect_language("a.py") == "python"
        assert detect_language("a.java") == "java"

    def test_unknown_extension(self):
        assert detect_language("a.rb") == ""
