"""Backward-compatibility shim. Import from core.errors instead."""

from core.errors import (
    AuthenticationError,
    CacheReadFailed,
    CacheWriteFailed,
    CompilationTimeout,
    DiffFetchFailed,
    InvalidDiff,
    InvalidWebhook,
    JSONSerializationFailed,
    LanguageDetectionFailed,
    LanguageNotSupported,
    MissingWebhookPayload,
    PipelineError,
    PipelineExecutionError,
    RendererFailed,
    RepositoryAccessDenied,
    RepositoryCompilationFailed,
    RepositoryNotFound,
    RepositoryNotInstalled,
    RepositoryNotSupported,
    WebhookVerificationError,
    RenderingError,
)

__all__ = [
    "AuthenticationError",
    "CacheReadFailed",
    "CacheWriteFailed",
    "CompilationTimeout",
    "DiffFetchFailed",
    "InvalidDiff",
    "InvalidWebhook",
    "JSONSerializationFailed",
    "LanguageDetectionFailed",
    "LanguageNotSupported",
    "MissingWebhookPayload",
    "PipelineError",
    "PipelineExecutionError",
    "RendererFailed",
    "RepositoryAccessDenied",
    "RepositoryCompilationFailed",
    "RepositoryNotFound",
    "RepositoryNotInstalled",
    "RepositoryNotSupported",
    "WebhookVerificationError",
    "RenderingError",
]
