"""Language-agnostic file role classification.

Classifies repository files into functional roles (frontend, backend, shared,
generated, ...) using deterministic path and content signals. Classification
is deliberately language-agnostic: a TypeScript file is NOT automatically a
frontend file, and no language plugin imports are required.

The classification model is consumed by two stages:

    ChangeCompiler
        └── FileClassificationPass   → analysis eligibility (changed files)
    RepositoryMaterializer
        └── FileClassifier + AnalysisPolicy → materialization eligibility

so that files which analysis would ignore are never paid for twice.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from enum import Enum


class FileKind(str, Enum):
    """Functional role of a repository file."""

    FRONTEND = "frontend"
    BACKEND = "backend"
    SHARED = "shared"
    GENERATED = "generated"
    CONFIG = "config"
    TEST = "test"
    MIGRATION = "migration"
    DOCS = "docs"
    INFRASTRUCTURE = "infrastructure"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class FileClassification:
    """Immutable classification result for a single file.

    kind        — the classified role.
    confidence  — deterministic confidence in [0.0, 1.0].
    reason      — human-readable explanation of the winning signal.
    """

    kind: FileKind
    confidence: float
    reason: str


# ---------------------------------------------------------------------------
# Analysis policy
# ---------------------------------------------------------------------------

FRONTEND_EXCLUDED_LANGUAGES = frozenset({"typescript", "javascript"})


def is_analyzable(
    classification: FileClassification,
    language: str,
) -> bool:
    """Decide whether a classified file is eligible for semantic change analysis.

    Policy (first implementation):
      * generated files are never analyzed;
      * frontend TypeScript/JavaScript is excluded from analysis;
      * everything else (including backend/shared TS) remains eligible.
    """
    if classification.kind == FileKind.GENERATED:
        return False

    return not (classification.kind == FileKind.FRONTEND and language in FRONTEND_EXCLUDED_LANGUAGES)


@dataclass(frozen=True)
class AnalysisPolicy:
    """Configurable analysis/materialization eligibility policy.

    The default policy excludes generated files of every language and
    frontend TS/JS. ``should_materialize`` is the lazy-materialization hook:
    it lets the RepositoryMaterializer skip remote fetches for files that
    ChangeCompiler analysis has already decided to ignore.
    """

    excluded_frontend_languages: frozenset[str] = FRONTEND_EXCLUDED_LANGUAGES
    exclude_generated: bool = True

    def is_analyzable(
        self,
        classification: FileClassification,
        language: str = "",
    ) -> bool:
        if self.exclude_generated and classification.kind == FileKind.GENERATED:
            return False

        return not (classification.kind == FileKind.FRONTEND and language in self.excluded_frontend_languages)

    def should_materialize(
        self,
        classification: FileClassification,
        language: str = "",
    ) -> bool:
        """Alias used by the materialization path; same policy as analysis."""
        return self.is_analyzable(classification, language)


DEFAULT_ANALYSIS_POLICY = AnalysisPolicy()


# ---------------------------------------------------------------------------
# Language hints (extension-based only; no language-plugin dependencies)
# ---------------------------------------------------------------------------

_LANGUAGE_BY_EXTENSION: dict[str, str] = {
    ".ts": "typescript",
    ".tsx": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".py": "python",
    ".java": "java",
}


def detect_language(path: str) -> str:
    """Best-effort language identifier from the file extension.

    Returns "" for unknown extensions. This is intentionally a pure string
    mapping so classification stays decoupled from language plugins.
    """
    _, ext = os.path.splitext(path)
    return _LANGUAGE_BY_EXTENSION.get(ext.lower(), "")


# ---------------------------------------------------------------------------
# Classifier signals
# ---------------------------------------------------------------------------

_GENERATED_PATH_SEGMENTS = frozenset(
    {"generated", "__generated__", "__generated", "gen", "autogenerated"}
)
_GENERATED_FILENAME_SUFFIXES = (
    "_pb2.py",
    "_pb2_grpc.py",
    ".pb.go",
    ".g.dart",
    ".gen.ts",
    ".generated.ts",
    ".min.js",
)
_GENERATED_CONTENT_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "do not edit",
)

_TEST_PATH_SEGMENTS = frozenset(
    {"tests", "test", "__tests__", "__mocks__", "spec", "specs"}
)
_TEST_FIXTURE_FILENAMES = frozenset({"conftest.py"})

_FRONTEND_PATH_SEGMENTS = frozenset({"frontend", "web", "client", "ui"})
_FRONTEND_DEEP_SEGMENTS = frozenset(
    {"components", "pages", "views", "screens", "widgets"}
)
_FRONTEND_EXTENSIONS = frozenset({".tsx", ".jsx"})

_BACKEND_PATH_SEGMENTS = frozenset(
    {"server", "backend", "api", "worker", "workers", "services"}
)

_SHARED_PATH_SEGMENTS = frozenset({"shared", "common", "libs"})

_CONFIG_EXTENSIONS = frozenset(
    {".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf", ".properties", ".env"}
)
_CONFIG_FILENAME_PATTERNS = ("makefile", "requirements.txt", ".editorconfig")
_CONFIG_STEM_SUFFIXES = (".config", ".rc")

_MIGRATION_PATH_SEGMENTS = frozenset(
    {"migrations", "migration", "alembic", "flyway", "liquibase"}
)

_DOCS_PATH_SEGMENTS = frozenset({"docs", "doc", "documentation", "wiki"})
_DOCS_EXTENSIONS = frozenset({".md", ".rst", ".adoc"})

_INFRASTRUCTURE_PATH_SEGMENTS = frozenset(
    {
        ".github",
        ".gitlab",
        ".circleci",
        ".teamcity",
        "terraform",
        "terragrunt",
        "k8s",
        "kubernetes",
        "helm",
        "infra",
        "infrastructure",
        "deploy",
        "deployments",
        "provisioning",
        "ci",
    }
)
_INFRASTRUCTURE_EXTENSIONS = frozenset({".tf", ".tfvars", ".dockerfile"})
_INFRASTRUCTURE_FILENAMES = frozenset(
    {"dockerfile", "jenkinsfile", "vagrantfile", ".gitlab-ci.yml"}
)
_INFRASTRUCTURE_FILENAME_PREFIXES = ("docker-compose",)


def _segments(path: str) -> tuple[str, ...]:
    normalized = normalize_classification_path(path)
    return tuple(p.lower() for p in normalized.split("/") if p)


def normalize_classification_path(path: str) -> str:
    """Normalize separators/leading components for signal matching."""
    p = path.replace("\\", "/")
    while p.startswith("./"):
        p = p[2:]
    return os.path.normpath(p).replace("\\", "/")


class FileClassifier:
    """Deterministic, language-agnostic file role classifier.

    Signals are evaluated in a fixed precedence order:

        generated markers
            ↓
        test markers
            ↓
        frontend path/framework signals
            ↓
        backend path/framework signals
            ↓
        shared path signals
            ↓
        config / migration / docs / infrastructure
            ↓
        unknown
    """

    def classify(
        self,
        path: str,
        content: str | None = None,
        metadata: dict | None = None,
    ) -> FileClassification:
        """Classify a file by path (and optionally its content).

        Args:
            path: Repository-relative file path.
            content: Optional decoded source text; enables generated-content
                marker detection before any fetch is required otherwise.
            metadata: Optional provider metadata dict (reserved for future
                signals such as explicit overrides); ignored when absent.
        """
        del metadata  # reserved for future explicit-override signals

        segs = _segments(path)
        filename = segs[-1] if segs else ""
        stem_no_ext, ext = os.path.splitext(filename)
        ext = ext.lower()
        dirs = set(segs[:-1])

        # 1. Generated markers take precedence over normal roles.
        generated = self._classify_generated(
            dirs, filename, stem_no_ext, ext, content
        )
        if generated is not None:
            return generated

        # 2. Test markers.
        test = self._classify_test(dirs, filename, stem_no_ext, ext)
        if test is not None:
            return test

        # 3. Frontend path/framework signals (.ts alone is never frontend).
        frontend = self._classify_frontend(dirs, ext)
        if frontend is not None:
            return frontend

        # 4. Backend path signals.
        if dirs & _BACKEND_PATH_SEGMENTS:
            return FileClassification(
                kind=FileKind.BACKEND,
                confidence=0.8,
                reason=f"path segment '{min(dirs & _BACKEND_PATH_SEGMENTS)}/'",
            )

        # 5. Shared path signals.
        if dirs & _SHARED_PATH_SEGMENTS:
            return FileClassification(
                kind=FileKind.SHARED,
                confidence=0.75,
                reason=f"path segment '{min(dirs & _SHARED_PATH_SEGMENTS)}/'",
            )

        # 6. Migration / infrastructure / docs / config signals.
        migration = self._classify_migration(dirs, filename, ext)
        if migration is not None:
            return migration

        infrastructure = self._classify_infrastructure(
            dirs, filename, stem_no_ext, ext
        )
        if infrastructure is not None:
            return infrastructure

        docs = self._classify_docs(dirs, ext)
        if docs is not None:
            return docs

        config = self._classify_config(filename, stem_no_ext, ext)
        if config is not None:
            return config

        # 7. No signals matched.
        return FileClassification(
            kind=FileKind.UNKNOWN,
            confidence=0.0,
            reason="no classification signals matched",
        )

    # -- individual signal groups ------------------------------------------

    def _classify_generated(
        self,
        dirs: set[str],
        filename: str,
        stem: str,
        ext: str,
        content: str | None,
    ) -> FileClassification | None:
        hit = dirs & _GENERATED_PATH_SEGMENTS
        if hit:
            return FileClassification(
                kind=FileKind.GENERATED,
                confidence=0.95,
                reason=f"generated path segment '{min(hit)}/'",
            )
        for suffix in _GENERATED_FILENAME_SUFFIXES:
            if filename.endswith(suffix):
                return FileClassification(
                    kind=FileKind.GENERATED,
                    confidence=0.9,
                    reason=f"generated filename suffix '{suffix}'",
                )
        if content:
            header = content[:4096].lower()
            for marker in _GENERATED_CONTENT_MARKERS:
                if marker in header:
                    return FileClassification(
                        kind=FileKind.GENERATED,
                        confidence=0.99,
                        reason=f"generated content marker '{marker}'",
                    )
        return None

    def _classify_test(
        self, dirs: set[str], filename: str, stem: str, ext: str
    ) -> FileClassification | None:
        hit = dirs & _TEST_PATH_SEGMENTS
        if hit:
            return FileClassification(
                kind=FileKind.TEST,
                confidence=0.9,
                reason=f"test path segment '{min(hit)}/'",
            )
        if filename in _TEST_FIXTURE_FILENAMES:
            return FileClassification(
                kind=FileKind.TEST,
                confidence=0.9,
                reason="test fixture file",
            )
        if (
            stem.startswith("test_")
            or stem.endswith("_test")
            or ".test." in filename
            or ".spec." in filename
        ):
            return FileClassification(
                kind=FileKind.TEST,
                confidence=0.85,
                reason=f"test filename pattern '{filename}'",
            )
        return None

    def _classify_frontend(self, dirs: set[str], ext: str) -> FileClassification | None:
        if ext in _FRONTEND_EXTENSIONS:
            return FileClassification(
                kind=FileKind.FRONTEND,
                confidence=0.85,
                reason=f"UI extension '{ext}'",
            )
        top = dirs & _FRONTEND_PATH_SEGMENTS
        if top:
            return FileClassification(
                kind=FileKind.FRONTEND,
                confidence=0.8,
                reason=f"frontend path segment '{min(top)}/'",
            )
        deep = dirs & _FRONTEND_DEEP_SEGMENTS
        if deep:
            return FileClassification(
                kind=FileKind.FRONTEND,
                confidence=0.8,
                reason=f"frontend path segment '{min(deep)}/'",
            )
        return None

    def _classify_migration(
        self, dirs: set[str], filename: str, ext: str
    ) -> FileClassification | None:
        hit = dirs & _MIGRATION_PATH_SEGMENTS
        if hit:
            return FileClassification(
                kind=FileKind.MIGRATION,
                confidence=0.8,
                reason=f"migration path segment '{min(hit)}/'",
            )
        if ext == ".sql" and filename[:1].upper() == "V" and "__" in stem_part(filename):
            return FileClassification(
                kind=FileKind.MIGRATION,
                confidence=0.8,
                reason="versioned migration filename pattern",
            )
        return None

    def _classify_infrastructure(
        self, dirs: set[str], filename: str, stem: str, ext: str
    ) -> FileClassification | None:
        hit = dirs & _INFRASTRUCTURE_PATH_SEGMENTS
        if hit:
            return FileClassification(
                kind=FileKind.INFRASTRUCTURE,
                confidence=0.8,
                reason=f"infrastructure path segment '{min(hit)}/'",
            )
        if ext in _INFRASTRUCTURE_EXTENSIONS or filename in _INFRASTRUCTURE_FILENAMES:
            return FileClassification(
                kind=FileKind.INFRASTRUCTURE,
                confidence=0.8,
                reason=f"infrastructure file '{filename}'",
            )
        if any(filename.startswith(p) for p in _INFRASTRUCTURE_FILENAME_PREFIXES):
            return FileClassification(
                kind=FileKind.INFRASTRUCTURE,
                confidence=0.75,
                reason=f"infrastructure file prefix '{filename}'",
            )
        return None

    def _classify_docs(self, dirs: set[str], ext: str) -> FileClassification | None:
        hit = dirs & _DOCS_PATH_SEGMENTS
        if hit:
            return FileClassification(
                kind=FileKind.DOCS,
                confidence=0.9,
                reason=f"docs path segment '{min(hit)}/'",
            )
        if ext in _DOCS_EXTENSIONS:
            return FileClassification(
                kind=FileKind.DOCS,
                confidence=0.85,
                reason=f"documentation extension '{ext}'",
            )
        return None

    def _classify_config(
        self, filename: str, stem: str, ext: str
    ) -> FileClassification | None:
        if ext in _CONFIG_EXTENSIONS:
            return FileClassification(
                kind=FileKind.CONFIG,
                confidence=0.7,
                reason=f"configuration extension '{ext}'",
            )
        lowered = filename.lower()
        if lowered in _CONFIG_FILENAME_PATTERNS:
            return FileClassification(
                kind=FileKind.CONFIG,
                confidence=0.8,
                reason=f"configuration file '{filename}'",
            )
        if stem.lower().endswith(_CONFIG_STEM_SUFFIXES):
            return FileClassification(
                kind=FileKind.CONFIG,
                confidence=0.7,
                reason=f"configuration filename pattern '{filename}'",
            )
        return None


def stem_part(filename: str) -> str:
    """Return the filename without its final extension."""
    stem, _ = os.path.splitext(filename)
    return stem
