"""Presentation Compiler — transforms engineering discovery into a representation optimized for human understanding."""

from .compiler import PresentationCompiler
from .compiler.passes import (
    PresentationPassContext,
    PresentationCompilationPass,
    NormalizationPass,
    DiscoveryExtractionPass,
    SignificanceEvaluationPass,
    RankingPass,
    SurpriseDetectionPass,
    CompressionPass,
    NarrativeConstructionPass,
    VisualCompositionPass,
    IRAssemblyPass,
)
from .model import (
    PresentationIR,
    PresentationDiscovery,
    PresentationEvidence,
    PresentationSummary,
    PresentationMetadata,
    PresentationNarrative,
    PresentationVisual,
    SignificanceMetrics,
    RankingVector,
    SurpriseVector,
    NormalizedDiscovery,
    DiscoveryKind,
    NarrativePosition,
    VisualSemantic,
)

__all__ = [
    "PresentationCompiler",
    "PresentationPassContext",
    "PresentationCompilationPass",
    "NormalizationPass",
    "DiscoveryExtractionPass",
    "SignificanceEvaluationPass",
    "RankingPass",
    "SurpriseDetectionPass",
    "CompressionPass",
    "NarrativeConstructionPass",
    "VisualCompositionPass",
    "IRAssemblyPass",
    "PresentationIR",
    "PresentationDiscovery",
    "PresentationEvidence",
    "PresentationSummary",
    "PresentationMetadata",
    "PresentationNarrative",
    "PresentationVisual",
    "SignificanceMetrics",
    "RankingVector",
    "SurpriseVector",
    "NormalizedDiscovery",
    "DiscoveryKind",
    "NarrativePosition",
    "VisualSemantic",
]
