"""Backward-compatibility shim. New code should import from engine.repository.model."""

from engine.repository.model import (
    Symbol,
    SymbolKind,
    SymbolVisibility,
    Evidence,
    FileLocation,
    SymbolReference,
    CallReference,
    ImportReference,
    AnnotationReference,
    CallEdge,
    CallGraph,
    ReferenceEdge,
    ReferenceGraph,
    TypeRelationshipEdge,
    TypeRelationshipGraph,
    RepositoryModel,
    EntryPoint,
    EntryPointKind,
    AsyncEntryPoint,
    PersistenceModel,
    PersistenceModelKind,
    RepositoryMethod,
    RepositoryMethodKind,
    EventConstruct,
    EventOperationKind,
    TestDefinition,
    TestFramework,
    TestFixture,
    ConfigurationReference,
    ConfigReferenceKind,
    RepositoryIndex,
    FileIndex,
    SymbolEntry,
    ImportEntry,
    RawReference,
    CallEntry,
    EntrypointEntry,
    TypeRelationshipEntry,
    PersistenceEntry,
    RepositoryMethodEntry,
    EventEntry,
    TestEntry,
    ConfigEntry,
    FileContribution,
    RepositoryGraph,
)

__all__ = [
    "Symbol", "SymbolKind", "SymbolVisibility",
    "Evidence", "FileLocation", "SymbolReference", "CallReference",
    "ImportReference", "AnnotationReference",
    "CallEdge", "CallGraph", "ReferenceEdge", "ReferenceGraph",
    "TypeRelationshipEdge", "TypeRelationshipGraph",
    "RepositoryModel", "EntryPoint", "EntryPointKind", "AsyncEntryPoint",
    "PersistenceModel", "PersistenceModelKind", "RepositoryMethod", "RepositoryMethodKind",
    "EventConstruct", "EventOperationKind",
    "TestDefinition", "TestFramework", "TestFixture",
    "ConfigurationReference", "ConfigReferenceKind",
    "RepositoryIndex", "FileIndex", "SymbolEntry", "ImportEntry", "RawReference",
    "CallEntry", "EntrypointEntry", "TypeRelationshipEntry", "PersistenceEntry",
    "RepositoryMethodEntry", "EventEntry", "TestEntry", "ConfigEntry",
    "FileContribution", "RepositoryGraph",
]
