from enum import Enum

class RiskEventType(str, Enum):
    AUTH_BYPASS = "AUTH_BYPASS"
    PERMISSION_REMOVED = "PERMISSION_REMOVED"
    FINANCIAL_LOGIC_CHANGE = "FINANCIAL_LOGIC_CHANGE"
    FINANCIAL_DATA_MODEL_CHANGE = "FINANCIAL_DATA_MODEL_CHANGE"
    TAX_CALCULATION_CHANGE = "TAX_CALCULATION_CHANGE"
    SCHEMA_MIGRATION = "SCHEMA_MIGRATION"
    DATA_BACKFILL = "DATA_BACKFILL"
    INVOICE_RENDERING_CHANGE = "INVOICE_RENDERING_CHANGE"
    DATA_LEAK_RISK = "DATA_LEAK_RISK"
    STATE_INCONSISTENCY = "STATE_INCONSISTENCY"
    BACKDOOR_INTRODUCED = "BACKDOOR_INTRODUCED"
    VALIDATION_REMOVED = "VALIDATION_REMOVED"
    CRITICAL_DEPENDENCY_CHANGED = "CRITICAL_DEPENDENCY_CHANGED"
    
class SignalType(str, Enum):
    AUTH_SURFACE = "AUTH_SURFACE"
    SESSION_FLOW = "SESSION_FLOW"
    PAYMENT_SURFACE = "PAYMENT_SURFACE"
    LOGIN_LOGOUT = "LOGIN_LOGOUT"
    VALIDATION_LOGIC = "VALIDATION_LOGIC"
    USER_INPUT = "USER_INPUT"
    CONFIG_CHANGE = "CONFIG_CHANGE"